[theme]
primaryColor = "#00FFFF"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#c9d1d9"
font = "monospace"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
